Update samplci.yml check deploly only v01

diff --git a/.github/workflows/samplci.yml b/.github/workflows/samplci.yml
--- a/.github/workflows/samplci.yml
+++ b/.github/workflows/samplci.yml
@@ -90,6 +90,10 @@ jobs:
       - name: Set Deploy Image 
         id: set_deploy_image
         run: |
+          if [ "${{ github.event_name }}" == "workflow_dispatch" ] && [ "${{ github.event.inputs.build_only != 'true' }}" ] && [ "${{ github.event.inputs.deploy_image_tag }}" == "v0.0.0" ]; then
+            echo "Error! No image tag provided for Deploy only Workflow"
+            exit 1
+          fi
           if [ "${{ github.event_name }}" == "workflow_dispatch" ] && [ "${{ github.event.inputs.deploy_image_tag }}" != "v0.0.0" ]; then
             echo "DEPLOY_IMAGE_TAG=${{ github.event.inputs.deploy_image_tag }}" >> "$GITHUB_OUTPUT"
           else
@@ -99,6 +103,7 @@ jobs:
       - name: Set Deploy Environment
         id: set_env
         run: |
+          
           if [ "${{ github.event_name }}" == "push" ] || [ "${{ github.event_name }}" == "pull_request" ]; then
             case ${{ steps.set_build_image.outputs.BRANCH_NAME }} in
               "dev")
@@ -129,29 +134,4 @@ jobs:
           echo "My deploy image : ${{ needs.set_build_params.outputs.DEPLOY_IMAGE_TAG }}"
           echo "My env : ${{ needs.set_build_params.outputs.DEPLOY_ENV }}"
           echo "My backend var: ${{ vars.WEB_APP_NAME }}"
-      
-      - uses: azure/login@v2
-        with:
-          creds: ${{ secrets.AZURE_CREDENTIALS }}
-
-      - name: Build Image
-        if: (github.event_name == 'workflow_dispatch' && github.event.inputs.build_only == 'true') || github.event_name != 'workflow_dispatch'
-        run: |
-            docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ vars.APP_NAME }}:${{ needs.set_build_params.outputs.BUILD_IMAGE_TAG }} .
-
-      - name: Get Runner IP
-        id: runner_ip
-        uses: haythem/public-ip@v1.3
-
-      - name: Allow ip
-        run: az acr network-rule add --name ritam0190 --ip-address ${{ steps.runner_ip.outputs.ipv4 }}
-
-
-      - name: Push Image
-        if: (github.event_name == 'workflow_dispatch' && github.event.inputs.build_only == 'true') || github.event_name != 'workflow_dispatch'
-        run: |
-          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ vars.APP_NAME }}:${{ needs.set_build_params.outputs.BUILD_IMAGE_TAG }}
-
-      - name: Remove ip 
-        run: az acr network-rule remove --name ritam0190 --ip-address ${{ steps.runner_ip.outputs.ipv4 }}
       
